---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: ''
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: ''
  label: Blocks
  create: all
  match: "**/*"
  templates:
  - blocks
- type: heading
  label: Heading label
- type: directory
  path: Here
  label: Directory
  create: all
  match: "**/*"
- type: document
  path: path
  label: label
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
